version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
  build:
    commands:
      - echo Build started
      - docker build -t my-app .
  post_build:
    commands:
      - echo Build completed
